/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Begle (https://sketchfab.com/begle)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stylized-keyboard-a9715f28ca0a411bb44747a89ca0ef42
title: Stylized Keyboard
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Keyboard(props: any) {
  const group = useRef();
  const { nodes, materials }: any = useGLTF("/assets/keyboard.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[5, 5, 50]}
          rotation={[-Math.PI / 5, 5, 0]}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="������������������002_1"
                position={[0.03, 1.07, 0.95]}
                rotation={[Math.PI, 0, Math.PI]}
              >
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials[".002"]}
                />
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials[".001"]}
                />
              </group>
              <group name="����������������_20" position={[0, 1.26, 0.98]}>
                <group
                  name="������003_19"
                  position={[0, -0.08, 0.12]}
                  scale={[0.44, 0.08, 0.04]}
                >
                  <mesh
                    name="Object_54"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_54.geometry}
                    material={materials[".003"]}
                  />
                </group>
              </group>
              <group name="����������������001_23" position={[0, 1.26, -0.87]}>
                <group
                  name="������������������001_21"
                  position={[0.03, -0.19, -0.01]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                >
                  <mesh
                    name="Object_58"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_58.geometry}
                    material={materials[".001"]}
                  />
                  <mesh
                    name="Object_57"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_57.geometry}
                    material={materials[".004"]}
                  />
                </group>
                <group
                  name="����������001_22"
                  position={[0.03, -0.08, 0]}
                  scale={0.66}
                >
                  <mesh
                    name="Object_60"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_60.geometry}
                    material={materials[".003"]}
                  />
                </group>
              </group>
              <group
                name="������������������_0"
                position={[0, 0.56, 0.01]}
                rotation={[-Math.PI, 0, -Math.PI]}
              >
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials[".002"]}
                />
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials[".001"]}
                />
              </group>
              <group
                name="��������������_2"
                position={[-1.83, 0.61, 0]}
                rotation={[-Math.PI, 0, -1.3]}
              >
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials[".004"]}
                />
                <mesh
                  name="Object_11"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials[".001"]}
                />
              </group>
              <group
                name="��������������001_3"
                position={[0, 0.61, -1.76]}
                rotation={[1.85, Math.PI / 2, 0]}
              >
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials[".004"]}
                />
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials[".001"]}
                />
              </group>
              <group
                name="��������������002_5"
                position={[-2.95, 0.09, -2.48]}
                rotation={[-Math.PI / 2, 0, 2.66]}
              >
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials[".004"]}
                />
                <mesh
                  name="Object_17"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_17.geometry}
                  material={materials[".001"]}
                />
              </group>
              <group
                name="������_6"
                position={[-3.09, 0.09, -2.2]}
                rotation={[Math.PI, -Math.PI / 3, Math.PI]}
              >
                <mesh
                  name="Object_19"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials[".004"]}
                />
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials[".001"]}
                />
              </group>
              <group
                name="������001_7"
                position={[-3.27, 0.09, -1.89]}
                rotation={[Math.PI, -Math.PI / 3, Math.PI]}
              >
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials[".005"]}
                />
                <mesh
                  name="Object_23"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials[".001"]}
                />
              </group>
              <group
                name="������002_8"
                position={[-3.27, 0.1, -1.89]}
                rotation={[Math.PI, -Math.PI / 3, Math.PI]}
              >
                <mesh
                  name="Object_25"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials[".005"]}
                />
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials[".001"]}
                />
              </group>
              <group
                name="����������_9"
                position={[-0.89, 1.18, -0.86]}
                scale={0.66}
              >
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials[".003"]}
                />
              </group>
              <group
                name="����������002_10"
                position={[0.96, 1.18, -0.87]}
                scale={0.66}
              >
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials[".003"]}
                />
              </group>
              <group
                name="����������003_11"
                position={[0.97, 1.18, 0.04]}
                scale={0.66}
              >
                <mesh
                  name="Object_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials[".003"]}
                />
              </group>
              <group
                name="����������004_12"
                position={[0.02, 1.18, 0.04]}
                scale={0.66}
              >
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials[".003"]}
                />
              </group>
              <group
                name="����������005_13"
                position={[-0.91, 1.18, 0.04]}
                scale={0.66}
              >
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials[".003"]}
                />
              </group>
              <group
                name="������������������003_14"
                position={[0.95, 1.07, -0.88]}
                rotation={[-Math.PI, 0, -Math.PI]}
              >
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials[".002"]}
                />
                <mesh
                  name="Object_39"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_39.geometry}
                  material={materials[".001"]}
                />
              </group>
              <group
                name="������������������004_15"
                position={[0.95, 1.07, 0.04]}
                rotation={[-Math.PI, 0, -Math.PI]}
              >
                <mesh
                  name="Object_41"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_41.geometry}
                  material={materials[".004"]}
                />
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials[".001"]}
                />
              </group>
              <group
                name="������������������005_16"
                position={[0.03, 1.07, 0.04]}
                rotation={[-Math.PI, 0, -Math.PI]}
              >
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials[".004"]}
                />
                <mesh
                  name="Object_45"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_45.geometry}
                  material={materials[".001"]}
                />
              </group>
              <group
                name="������������������006_17"
                position={[-0.9, 1.07, 0.04]}
                rotation={[-Math.PI, 0, -Math.PI]}
              >
                <mesh
                  name="Object_47"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_47.geometry}
                  material={materials[".004"]}
                />
                <mesh
                  name="Object_48"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials[".001"]}
                />
              </group>
              <group
                name="������������������007_18"
                position={[-0.9, 1.07, -0.88]}
                rotation={[-Math.PI, 0, -Math.PI]}
              >
                <mesh
                  name="Object_50"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials[".002"]}
                />
                <mesh
                  name="Object_51"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_51.geometry}
                  material={materials[".001"]}
                />
              </group>
              <group
                name="����������������������001_24"
                position={[-1.48, 0.43, -2.2]}
                rotation={[0, -1.4, 0]}
              >
                <mesh
                  name="Object_62"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials[".004"]}
                />
                <mesh
                  name="Object_63"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_63.geometry}
                  material={materials[".001"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/keyboard.gltf");
